spring.application.name=springAiConversational


server.port=${PORT_NO}

spring.ai.openai.api-key=${API_KEY}
spring.ai.openai.base-url=${BASE_URL}

spring.ai.openai.chat.options.model=${MODEL_NAME}

spring.ai.openai.chat.options.temperature=0.5
